apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease
  template:
    metadata:
      labels:
        app: heart-disease
    spec:
      containers:zzzzzzzzz  
      - name: heart-disease-container
        image: bhavanimish/heart-disease-ml:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
spec:
  selector:
    app: heart-disease
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
