name: ML CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ipykernel
      run: |
        pip install ipykernel

    - name: Install Jupyter and create a kernel
      run: |
        pip install jupyter
        python -m ipykernel install --user --name=python3 --display-name "Python 3"

    - name: Check installed Python kernels
      run: |
        jupyter kernelspec list

    - name: Run Jupyter notebook (optional)
      run: |
        pip install nbconvert
        jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 heart.ipynb --output executed_notebook.ipynb
